### ISSUE TITLE
Detect tests in tests/ folder

### ISSUE THREAD

**Issue by remidebette** [swellaby/vscode-rust-test-adapter#92]
Hi,

Thanks for the nice extension.

I tried to use the "workspace" model where several members each have a Cargo.toml file.

Only the tests inside #[cfg(test)] modules are detected. 
When putting tests in a tests/ folder in any member, they are properly picked by a `cargo test`, but not by the extension.

**Comment by calebcartwright** [comment]
Thanks for reaching out and the kind words! We don't support discovery and execution integration tests yet (only unit tests) which is why you're seeing this behavior. 

Support for integration tests is covered #3 so I'm going to close this one to avoid duplication, feel free to subscribe to that other issue for updates.
