### ISSUE TITLE
Tests in the "Tests" folder are not discovered and runnable.

### ISSUE THREAD

**Issue by gbutler69** [swellaby/vscode-rust-test-adapter#97]
As of version 0.11.x the tests that are in the "tests" folder of a project are not discovered. Only unit tests in the same file as the code under test (lib) are discovered and runnable.

**Comment by calebcartwright** [comment]
Thanks for using the extension and reaching out! I am going to go ahead and close this though because the fact that integration tests aren't yet supported is already known and documented, making this duplicative.

On the issues side, this duplicates #3 so you may want to subscribe to that issue to receive any updates. The documentation in the readme file also enumerates [current features](https://github.com/swellaby/vscode-rust-test-adapter#current-features) (unit tests) as well as [unsupported features on the roadmap](https://github.com/swellaby/vscode-rust-test-adapter#roadmap) (including integration tests)
